import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { experiences } from "../../data/experience";
import Container from "../../layout/Container";
import SectionHeading from "../../components/SectionHeading";
import TechBadge from "../../components/TechBadge";
function Experience() {
    return (_jsx("section", { id: "experiencia", "aria-labelledby": "heading-experiencia", className: "py-24", children: _jsxs(Container, { children: [_jsx(SectionHeading, { id: "heading-experiencia", title: "Experiencia" }), _jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute left-4 top-0 h-full w-0.5 bg-slate-800 md:left-1/2 md:-translate-x-px" }), experiences.map((exp, index) => (_jsxs(motion.div, { initial: { y: 30, opacity: 0 }, whileInView: { y: 0, opacity: 1 }, viewport: { once: true, margin: "-80px" }, transition: { duration: 0.5, delay: index * 0.1, ease: "easeOut" }, className: "relative mb-8 pl-10 md:w-1/2 md:pl-0 md:odd:pr-12 md:even:ml-auto md:even:pl-12", children: [_jsx("span", { className: "absolute left-1.5 top-2 h-3 w-3 rounded-full border-2 border-primary bg-background md:left-auto md:odd:right-[-7px] md:even:left-[-7px]" }), _jsxs("div", { className: "rounded-xl bg-card p-6", children: [_jsx("span", { className: "mb-2 inline-block text-sm font-medium text-primary", children: exp.period }), _jsx("h3", { className: "mb-1 text-lg font-semibold text-white", children: exp.company }), _jsx("p", { className: "mb-3 text-sm font-medium text-slate-400", children: exp.role }), exp.clients && exp.clients.length > 0 && (_jsxs("p", { className: "mb-3 text-sm text-slate-500", children: ["Clientes: ", exp.clients.join(", ")] })), exp.description && (_jsx("p", { className: "mb-4 text-sm leading-relaxed text-slate-400", children: exp.description })), _jsx("div", { className: "flex flex-wrap gap-1.5", children: exp.stack.map((tech) => (_jsx(TechBadge, { label: tech }, tech))) })] })] }, `${exp.company}-${exp.period}`)))] })] }) }));
}
export default Experience;
