import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { profile } from "../../data/profile";
import Container from "../../layout/Container";
import SectionHeading from "../../components/SectionHeading";
import TechBadge from "../../components/TechBadge";
function About() {
    return (_jsx("section", { id: "sobre-mi", "aria-labelledby": "heading-sobre-mi", className: "py-24", children: _jsxs(Container, { children: [_jsx(SectionHeading, { id: "heading-sobre-mi", title: "Sobre m\u00ED" }), _jsxs("div", { className: "grid gap-12 lg:grid-cols-2", children: [_jsx(motion.div, { initial: { y: 30, opacity: 0 }, whileInView: { y: 0, opacity: 1 }, viewport: { once: true, margin: "-80px" }, transition: { duration: 0.6, delay: 0.1, ease: "easeOut" }, className: "space-y-4", children: profile.biography.split("\n\n").map((paragraph, index) => (_jsx("p", { className: "text-base leading-relaxed text-slate-400", children: paragraph }, index))) }), _jsxs(motion.div, { initial: { y: 30, opacity: 0 }, whileInView: { y: 0, opacity: 1 }, viewport: { once: true, margin: "-80px" }, transition: { duration: 0.6, delay: 0.2, ease: "easeOut" }, className: "space-y-8", children: [_jsxs("div", { className: "rounded-xl bg-card p-6", children: [_jsx("h3", { className: "mb-1 text-sm font-medium uppercase tracking-wider text-slate-500", children: "Experiencia" }), _jsxs("p", { className: "text-3xl font-bold text-white", children: [profile.yearsOfExperience, "+"] }), _jsx("p", { className: "text-sm text-slate-400", children: "a\u00F1os de experiencia" })] }), _jsxs("div", { className: "rounded-xl bg-card p-6", children: [_jsx("h3", { className: "mb-1 text-sm font-medium uppercase tracking-wider text-slate-500", children: "Ubicaci\u00F3n" }), _jsxs("p", { className: "text-lg font-medium text-white", children: [profile.location.city, ", ", profile.location.region] }), _jsx("p", { className: "text-sm text-slate-400", children: profile.location.country })] }), _jsxs("div", { className: "rounded-xl bg-card p-6", children: [_jsx("h3", { className: "mb-4 text-sm font-medium uppercase tracking-wider text-slate-500", children: "Especialidades" }), _jsx("ul", { className: "space-y-2", children: profile.specialties.map((specialty) => (_jsxs("li", { className: "flex items-start gap-2 text-sm text-slate-300", children: [_jsx("span", { className: "mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" }), specialty] }, specialty))) })] }), _jsxs("div", { className: "rounded-xl bg-card p-6", children: [_jsx("h3", { className: "mb-4 text-sm font-medium uppercase tracking-wider text-slate-500", children: "Tecnolog\u00EDas principales" }), _jsx("div", { className: "flex flex-wrap gap-2", children: profile.mainTechnologies.map((tech) => (_jsx(TechBadge, { label: tech }, tech))) })] })] })] })] }) }));
}
export default About;
